host: "http://127.0.0.1:3000"

jwtSecret: "lenjoy"

mysql:
  host: "127.0.0.1"
  port: 3306
  database: "lenjoy"
  username: "root"
  password: "lenjoy123"

redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  password: "lenjoy123"

qiniu:
  ak: uzkvFPeBGf6Zuz2RfoQTfeDFOYTOxloHkcMK26Tb
  sk: 6Z4hR1RqQFd6IlN4-vc0CJ8ObJZFMWXTobyaOu34
  bucket: lenjoy-dev
  host: http://qiniu.lenjoy.top

email:
  from: "lenjoy007@163.com"
